---
platform: linux
inputs:
  - name: source-repo
image_resource:
  type: docker-image
  source: {repository: testcafe/testcafe}
  tag: "latest"
run:
  path: sh 
  args:
    - -exc
    - |
      echo 'helloworld'
      testcafe --version
      testcafe chrome ./source-repo/tests/test.js