---
platform: linux
inputs:
  - name: source-repo
image_resource:
  type: docker-image
  source:              
    repository: busybox
    tag: "latest"    
  run:
    path: sh 
    args:	
    - -exc	
    - |	
      echo 'helloworld'