---
platform: linux
image_resource:
  type: docker-image
  source: 
    repository: testcafe/testcafe
    tag: "latest"
run:
  path: sh 
  args:
    - -exc
    - |
      echo 'helloworld'
      testcafe --version